services:
  - type: web
    name: ai-flood-prediction-system
    env: python
    buildCommand: pip install -r requirements-production.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
